name: Snake Animation

on:
  push:
    branches:
      - main 

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user: KRSNAGUPTA  
          svg_out_path: output/snake.svg 
