name: Snake Animation

on:
  push:
    branches:
      - main  # You can change this to your default branch if it's not 'main'

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user: KRSNAGUPTA  # Replace with your GitHub username
          svg_out_path: output/snake.svg  # Path to save the generated snake.svg
